spring.application.name=E-commerce

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/banhang
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.signerKey=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkhvYW5nIFR1b25nIiwiaWF0IjoxNzcyMTYyMTAzLCJleHAiOjE3NzIxNjU3MDN9.jZ86eR5rqKO4qR3tD0m07CLMD7xQCvdiiQcruyb0pBA
jwt.expiration=3600000

app.admin.email=admin
app.admin.password=admin@gmail.com

# Cloudinary
cloudinary.cloud-name=cellphones-shop
cloudinary.api-key=412876966384479
cloudinary.api-secret=0_3UOiMZf7HlCZmd3fM4okSm-oA
cloudinary.folder=ecommerce

#Mail
app.mail.from=tuonganhdev186@gmail.com
app.verification.code.length=6
app.verification.expiry.minutes=10
app.verification.resend.cooldown.seconds=60

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tuonganhdev186@gmail.com
spring.mail.password=gqni tluj ukrv icxe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
